import { PDFDocument, PageSizes, rgb, type PDFFont } from "pdf-lib";
import fontkit from "@pdf-lib/fontkit";
import { readFile } from "node:fs/promises";
import { join } from "node:path";

/** Stored at settlement. Never rebuild a receipt from current profiles, rates,
 * recipients or fee settings. No banking credentials or identity documents. */
export type RequestCompletionReceiptSnapshot = {
  version: 1;
  request_id: string;
  transaction_id: string;
  reference_code: string;
  completed_at: string;
  sender_name: string;
  recipient_name: string;
  funding_currency: "AUD" | "IRT";
  funding_total: number | string;
  recipient_currency: "AUD" | "IRT";
  recipient_amount: number | string;
  base_fee_aud: number | string;
  priority_fee_aud: number | string;
  priority_fee_amount: number | string;
  priority_fee_status: string;
  applied_rate: number | string;
  service_tier: "standard" | "priority";
};

export function validateRequestReceipt(value: RequestCompletionReceiptSnapshot): void {
  if (!value || value.version !== 1 || !/^[0-9a-f-]{36}$/i.test(value.request_id)
    || !/^[0-9a-f-]{36}$/i.test(value.transaction_id)
    || !Number.isFinite(Date.parse(value.completed_at))
    || !["standard", "priority"].includes(value.service_tier)
    || !["AUD", "IRT"].includes(value.funding_currency) || !["AUD", "IRT"].includes(value.recipient_currency)) {
    throw new Error("invalid_completion_receipt");
  }
  for (const key of ["reference_code", "sender_name", "recipient_name"] as const) {
    if (typeof value[key] !== "string" || !value[key].trim() || value[key].length > 500 || /[\u0000-\u001f]/.test(value[key])) {
      throw new Error("invalid_completion_receipt");
    }
  }
  for (const key of ["funding_total", "recipient_amount", "base_fee_aud", "priority_fee_aud", "priority_fee_amount", "applied_rate"] as const) {
    if (!["string", "number"].includes(typeof value[key]) || String(value[key]).trim() === "" || !Number.isFinite(Number(value[key])) || Number(value[key]) < 0) {
      throw new Error("invalid_completion_receipt");
    }
  }
  if (Number(value.funding_total) <= 0 || Number(value.recipient_amount) <= 0 || Number(value.applied_rate) <= 0) throw new Error("invalid_completion_receipt");
}

export function receiptAmount(amount: number | string, currency: "AUD" | "IRT"): string {
  return `${currency === "IRT" ? "Toman (IRT)" : "AUD"} ${Number(amount).toLocaleString("en-AU", { minimumFractionDigits: currency === "AUD" ? 2 : 0, maximumFractionDigits: 2 })}`;
}

export function requestReceiptRows(receipt: RequestCompletionReceiptSnapshot): [string, string][] {
  validateRequestReceipt(receipt);
  return [
    ["Reference", receipt.reference_code],
    ["Completed (Sydney time)", new Date(receipt.completed_at).toLocaleString("en-AU", { timeZone: "Australia/Sydney", dateStyle: "medium", timeStyle: "short" })],
    ["Sender", receipt.sender_name],
    ["Recipient", receipt.recipient_name],
    ["Total funding received", receiptAmount(receipt.funding_total, receipt.funding_currency)],
    ["Recipient payout", receiptAmount(receipt.recipient_amount, receipt.recipient_currency)],
    ["Accepted exchange rate", `${Number(receipt.applied_rate).toLocaleString("en-AU")} Toman per AUD`],
    ["Service", receipt.service_tier === "priority" ? "Priority" : "Standard"],
    ["Base fee (AUD equivalent)", receiptAmount(receipt.base_fee_aud, "AUD")],
    ["Additional priority fee", receiptAmount(receipt.priority_fee_amount, receipt.funding_currency)],
    ...(receipt.service_tier === "priority" ? [["Priority fee status at completion", receipt.priority_fee_status.replace(/_/g, " ")] as [string, string]] : []),
  ];
}

/** Bilingual names are kept intact using the site's embedded Persian font.
 * Creation/modification dates are pinned to settlement, and the outbox stores
 * the generated bytes before sending so provider retries are byte-identical. */
export async function renderRequestReceiptPdf(receipt: RequestCompletionReceiptSnapshot): Promise<Uint8Array> {
  const rows = requestReceiptRows(receipt);
  const doc = await PDFDocument.create();
  doc.registerFontkit(fontkit);
  doc.setTitle(`Zarman receipt ${receipt.reference_code}`);
  doc.setAuthor("Zarman Exchange");
  doc.setCreator("Zarman Exchange");
  doc.setProducer("Zarman Exchange");
  doc.setCreationDate(new Date(receipt.completed_at));
  doc.setModificationDate(new Date(receipt.completed_at));
  const [regularBytes, boldBytes] = await Promise.all([
    readFile(join(process.cwd(), "public/fonts/IRANSansX-Regular.ttf")),
    readFile(join(process.cwd(), "public/fonts/IRANSansX-Bold.ttf")),
  ]);
  const regular = await doc.embedFont(regularBytes, { subset: true });
  const bold = await doc.embedFont(boldBytes, { subset: true });
  const ink = rgb(0.06, 0.09, 0.16), muted = rgb(0.35, 0.40, 0.46), accent = rgb(0.07, 0.37, 0.35);
  let page = doc.addPage(PageSizes.A4);
  const width = page.getWidth();
  let y = 682;
  const drawHeader = () => {
    page.drawRectangle({ x: 0, y: 716, width, height: 126, color: ink });
    page.drawText("ZARMAN EXCHANGE", { x: 42, y: 790, font: bold, size: 23, color: rgb(1, 1, 1) });
    page.drawText("Completed transfer receipt", { x: 42, y: 752, font: regular, size: 17, color: rgb(0.8, 0.91, 0.9) });
  };
  const wrap = (text: string, font: PDFFont, size: number, maxWidth: number) => {
    const lines: string[] = [];
    let line = "";
    for (const char of text) {
      if (line && font.widthOfTextAtSize(line + char, size) > maxWidth) { lines.push(line); line = ""; }
      line += char;
    }
    if (line) lines.push(line);
    return lines;
  };
  drawHeader();
  for (const [label, value] of rows) {
    const lines = wrap(value, regular, 11, width - 262);
    const rowHeight = Math.max(32, lines.length * 16 + 14);
    if (y - rowHeight < 94) { page = doc.addPage(PageSizes.A4); drawHeader(); y = 682; }
    page.drawText(label, { x: 42, y, font: bold, size: 10, color: muted });
    lines.forEach((line, index) => page.drawText(line, { x: 224, y: y - index * 16, font: regular, size: 11, color: ink }));
    y -= rowHeight;
    page.drawLine({ start: { x: 42, y: y + 12 }, end: { x: width - 42, y: y + 12 }, color: rgb(0.86, 0.89, 0.90), thickness: 0.5 });
  }
  for (const receiptPage of doc.getPages()) {
    receiptPage.drawText("Issued after verified settlement. Keep this receipt for your records.", { x: 42, y: 60, font: regular, size: 9, color: accent });
    receiptPage.drawText("Zarman Exchange  |  www.zarman.com.au", { x: 42, y: 42, font: regular, size: 9, color: muted });
  }
  return doc.save();
}
