export type RequestLocale = "en" | "fa";
export type ServiceTier = "standard" | "priority";
export type RequestStatus = "submitted" | "under_review" | "action_required" | "awaiting_funds" | "ready" | "processing" | "reconciliation" | "completed" | "cancelled" | "rejected" | "expired";
export type RequestCommand = "review" | "request_info" | "respond" | "await_funds" | "confirm_funds" | "start_processing" | "record_uncertain_payout" | "complete" | "cancel" | "reject" | "confirm_refund" | "payment_evidence";
export type ActionResult<T> = { data: T; error?: never } | { error: string; data?: never };

export type RequestSettings = {
  enabled: boolean;
  priority_enabled: boolean;
  priority_fee_aud: number;
  priority_capacity: number;
  standard_minutes: number;
  priority_minutes: number;
  quote_minutes: number;
  funding_minutes: number;
  max_amount_aud: number;
  timezone: "Australia/Sydney";
  business_days: number[];
  opening_hour: number;
  closing_hour: number;
  holidays: string[];
  management_emails: string[];
  payment_instructions_aud: string;
  payment_instructions_irt: string;
  priority_terms: string;
  priority_terms_fa: string;
};
export type SettingsRecord = { version: number; settings: RequestSettings };
export type PublicRequestSettings = Omit<RequestSettings, "management_emails" | "payment_instructions_aud" | "payment_instructions_irt">;

export type QuoteInput = {
  rawAmount: number;
  txType: "buy_aud" | "sell_aud";
  sourceOfFunds: string;
  reasonForTransfer: string;
  recipientId: string;
  promoCode?: string | null;
  paymentLink?: string | null;
  institutionName?: string;
  invoiceReference?: string;
  serviceTier: ServiceTier;
  locale: RequestLocale;
};
export type QuoteSnapshot = {
  locale: RequestLocale;
  customer_request_type: "buy_aud" | "sell_aud";
  company_trade_type: "buy_aud" | "sell_aud";
  raw_amount_aud: number;
  equivalent_toman: number;
  applied_rate: number;
  base_fee_aud: number;
  priority_fee_aud: number;
  priority_fee_amount: number;
  funding_currency: "AUD" | "IRT";
  funding_total: number;
  recipient_amount: number;
  recipient_currency: "AUD" | "IRT";
  service_tier: ServiceTier;
  source_of_funds: string;
  reason_for_transfer: string;
  recipient_id: string | null;
  recipient_snapshot: Record<string, unknown>;
  sender_snapshot: { name: string; email: string };
  payment_link: string | null;
  institution_name: string | null;
  invoice_reference: string | null;
  promo_code: string | null;
  promo_snapshot: Record<string, unknown> | null;
  discount_amount: number;
  loyalty_discount: number;
  policy_version: number;
  policy_snapshot: PublicRequestSettings;
  rate_id: string;
};
export type RequestQuote = { id: string; user_id: string; snapshot: QuoteSnapshot; expires_at: string; created_at: string };
export type ExchangeRequest = {
  id: string;
  transaction_id: string;
  user_id: string;
  reference_code: string;
  status: RequestStatus;
  version: number;
  quote: QuoteSnapshot;
  service_tier: ServiceTier;
  priority_fee_status: "not_applicable" | "unpaid" | "paid" | "refund_pending" | "refunded";
  funding_status: "unpaid" | "partial" | "confirmed" | "refund_pending" | "refunded";
  funding_received: number;
  payment_instructions: string | null;
  action_required: string | null;
  owner_id: string | null;
  handling_due_at: string | null;
  handling_started_at: string | null;
  funding_due_at: string;
  ready_at: string | null;
  created_at: string;
  updated_at: string;
};
export type RequestEvent = { id: string; request_id: string; sequence: number; event_type: string; status: RequestStatus; public_message: string | null; actor_id: string | null; created_at: string };
export type RequestDelivery = { id: string; event_id: string; request_id: string; audience: "customer" | "management"; recipient_email: string; locale: RequestLocale; status: string; attempts: number; last_error: string | null; created_at: string };
export type RequestDetail = { request: ExchangeRequest; events: RequestEvent[]; deliveries?: RequestDelivery[] };
export type RequestMutationInput = {
  requestId: string;
  expectedVersion: number;
  commandKey: string;
  action: RequestCommand;
  payload?: {
    message?: string;
    payment_reference?: string;
    received_amount?: number;
    received_currency?: "AUD" | "IRT";
    settlement_reference?: string;
    payer_account_id?: string;
    receiver_account_id?: string;
    transfer_method?: string;
    refund_reference?: string;
    refund_kind?: "priority" | "principal";
  };
};
